---
# Demo ACI Playbook
- name: Configuring Example Tenant
  hosts: apic1
  connection: local
  gather_facts: no

  tasks:
  - name: Create a New Tenant
    aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: ansible
        private_key: ansible.key
        tenant: "Cert"
        description: "Tenant configured by Ansible with Signature-based auth"
        validate_certs: no
        state: present

